linters:
  enable:
  - gosec
  - unconvert
  - goconst
  - gocyclo
  - asciicheck
  - misspell
  - lll
  - unparam
  - dogsled
  - nakedret
  - prealloc
  - gocritic
  - godox
  - funlen
  - whitespace
  - gomnd
  - godot
  - nestif
  - nolintlint
  - bodyclose
  - cyclop
  - dogsled
  - durationcheck
  - errorlint
  - exhaustive
  - exportloopref
  - forcetypeassert
  - importas
  - makezero
  - nilerr
  - noctx
  - predeclared
  - tagliatelle
  - revive
  - ifshort
  - asasalint
  - decorder
  - errchkjson
  - errname
  - execinquery
  - grouper
  - maintidx
  - nilnil
  - nonamedreturns
  - nosprintfhostport
  - tenv
  - usestdlibvars
  disable-all: false
  fast: false
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forcetypeassert
    - linters:
        - lll
      source: "^//.*https://.*" # Exclude links from line length check
