# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

global:
  registry: keppel.eu-de-1.cloud.sap
replicaCount: 2
image:
  repository: ccloud/maintenance-controller
  tag: $TAG
  pullPolicy: Always
rbac:
  create: true
  serviceAccountName: maintenance-controller
flatcar-linux-update-agent:
  image:
    repository: ccloud/flatcar-linux-update-operator
    tag: 9b00307910f2930c9cddde22246d417e7d2fe346
  rbac:
    create: true
    serviceAccountName: flatcar-linux-update-agent
kubernikus:
  enabled: true
  config: |
    intervals:
      requeue: 2s
      podDeletion:
        period: 20s
        timeout: 5m
      podEviction:
        period: 20s
        timeout: 5m
config: |
  intervals:
    requeue: 10s
    notify: 5h
  dashboard:
    labelFilter:
    - "kubernetes.io/hostname"
    - "kubernetes.io/os"
  instances:
      notify: null
      check:
      - type: hasAnnotation
        name: reboot_needed
        config:
          key: flatcar-linux-update.v1.flatcar-linux.net/reboot-needed
          value: ${TRUE}
      - type: hasAnnotation
        name: check_approval
        config:
          key: cloud.sap/maintenance-approved
          value: ${TRUE}
      - type: kubernikusCount
        name: check_kubernikus
        config:
          cluster: "maintenance-con-e2e"
      trigger:
      - type: alterAnnotation
        name: reboot-ok
        config:
          key: flatcar-linux-update.v1.flatcar-linux.net/reboot-ok
          value: ${TRUE}
      - type: alterAnnotation
        name: remove_approval
        config:
          key: cloud.sap/maintenance-approved
          remove: true
      - type: alterAnnotation
        name: remove_reboot_ok
        config:
          key: flatcar-linux-update.v1.flatcar-linux.net/reboot-ok
          remove: true
  profiles:
  - name: flatcar
    operational:
      transitions:
      - check: reboot_needed
        next: maintenance-required
    maintenance-required:
      transitions:
      - check: check_approval && check_kubernikus
        trigger: remove_approval && reboot-ok
        next: in-maintenance
    in-maintenance:
      transitions:
      - check: "!reboot_needed"
        trigger: remove_reboot_ok
        next: operational
# to test interpolation
secrets:
  "TRUE": "true"
