name: Build and run tests
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  lint:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # always uses the latest patch version.
          version: v1.52
          args: "--timeout 5m"
  
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...
  
  test:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache testbin binaries
        id: cache-testbin
        uses: actions/cache@v3
        with:
          path: testbin
          # Use SHA-256 hash of the Makefile file as the key.
          # Swapping testbinary versions usally requrie to change the Makefile
          key: ${{ runner.os }}-kubebuilder-${{ hashFiles('Makefile') }}

      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.9.2

      - name: Run tests and generate coverage
        run: |
          ENVTEST_K8S_VERSION=1.25.0 make test

      - name: Upload coverage results to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverprofile.out
